document.write("Table of 4" + "<br>");
document.write("4" + "x" + "1" + "=" + 2 * 1 + "<br>");
document.write("4" + "x" + "2" + "=" + 2 * 2 + "<br>");
document.write("4" + "x" + "3" + "=" + 2 * 3 + "<br>");
document.write("4" + "x" + "4" + "=" + 2 * 4 + "<br>");
document.write("4" + "x" + "5" + "=" + 2 * 5 + "<br>");
document.write("4" + "x" + "6" + "=" + 2 * 6 + "<br>");
document.write("4" + "x" + "7" + "=" + 2 * 7 + "<br>");
document.write("4" + "x" + "8" + "=" + 2 * 8 + "<br>");
document.write("4" + "x" + "9" + "=" + 2 * 9 + "<br>");
document.write("4" + "x" + "10" + "=" + 2 * 10 + "<br>");