var a=+prompt("Enter the First number");
var b=+prompt("Enter the Second number");
var c=a+b;
var d=a-b;
var e=a*b;
var f=a/b;
var g=a%b;
document.write("<h1>Calculator</h1>");
document.write("Sum of         "  ,  + a , "  and  "  ,b + "  is   " ,c + "<br>");      
document.write(" Differnce of         "  ,  + a , "  and  "  ,b + "  is   " ,d + "<br>");
document.write("   Product of         "  ,  + a , "  and  "  ,b + "  is   " ,e + "<br>");
document.write("  Division of         "  ,  + a , "  and  "  ,b + "  is   " ,f + "<br>");
document.write("   modulus of         "  ,  + a , "  and  "  ,b + "  is   " ,g + "<br>");
